#!/usr/bin/env python3
"""Generate databricks/dashboards/dashboard_queries.sql from the dashboard JSON.

The JSON is the single executed source of truth; this file is a readable
export of its dataset queries. Regenerated by deploy-dashboard-ce.sh and
guard-tested (test_dashboard_spec.py) so it cannot drift.
"""

from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DASHBOARD_JSON = ROOT / "databricks" / "dashboards" / "sales_overview.lvdash.json"
OUT = ROOT / "databricks" / "dashboards" / "dashboard_queries.sql"

HEADER = """-- Dashboard dataset queries — GENERATED from sales_overview.lvdash.json
-- by scripts/gen_dashboard_queries.py. Do not edit by hand: the JSON is the
-- executed source of truth, and a test fails if this file drifts from it.
-- Table names are bare on purpose: the catalog and schema are supplied at
-- deploy time (--dataset-catalog de_assessment --dataset-schema gold).
"""


def render() -> str:
    spec = json.loads(DASHBOARD_JSON.read_text(encoding="utf-8"))
    parts = [HEADER]
    for ds in spec["datasets"]:
        parts.append(f"\n-- {ds['name']}: {ds.get('displayName', '')}\n")
        parts.append("".join(ds["queryLines"]).rstrip() + ";\n")
    return "".join(parts)


if __name__ == "__main__":
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT}")
